# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm25', '0002_auto_20161224_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='local_time',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
