# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm25', '0004_auto_20161224_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airquality',
            name='local_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
